# Generated by Django 2.2 on 2021-03-01 02:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Deporte',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=220)),
                ('descripcion', models.CharField(max_length=220)),
                ('tipo', models.CharField(max_length=220)),
                ('icono', models.CharField(max_length=220)),
            ],
            options={
                'verbose_name_plural': 'Deportes',
            },
        ),
        migrations.CreateModel(
            name='Deportista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de Nacimiento')),
                ('peso', models.FloatField(help_text='Peso del Deportista', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('estatura', models.FloatField(help_text='Estatura del Deportista', validators=[django.core.validators.MinValueValidator(0.0)])),
                ('entrenador', models.CharField(help_text='Entrenador del Deportista', max_length=128)),
                ('imagen', models.URLField(help_text='URL Foto de Perfil', verbose_name='Foto')),
            ],
            options={
                'verbose_name_plural': 'Deportistas',
            },
        ),
        migrations.CreateModel(
            name='Lugar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departamento', models.CharField(max_length=50)),
                ('ciudad', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Lugares',
            },
        ),
        migrations.CreateModel(
            name='Participacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha')),
                ('hora', models.TimeField(verbose_name='Hora')),
                ('modalidad', models.CharField(max_length=220)),
                ('resultado', models.FloatField(blank=True, null=True)),
                ('deporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Deporte')),
                ('deportista', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Deportista')),
            ],
            options={
                'verbose_name_plural': 'Participaciones',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='URL del video', verbose_name='Video')),
                ('participacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='portal.Participacion')),
            ],
            options={
                'verbose_name_plural': 'Videos',
            },
        ),
        migrations.AddField(
            model_name='deportista',
            name='lugar_nacimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Lugar'),
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=1000)),
                ('fecha', models.DateTimeField()),
                ('usuario_registrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portal.Video')),
            ],
            options={
                'verbose_name_plural': 'Comentarios',
            },
        ),
    ]
