# Generated by Django 2.2 on 2021-03-01 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='username',
            field=models.CharField(default='Anonymous', max_length=250),
            preserve_default=False,
        ),
    ]
