# Generated by Django 2.2 on 2021-03-01 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20210216_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deportista',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
    ]
